export const matches = [
  {
    "competition_id": 0,
    "competition": "Michaelmas Cup",
    "season_end_year": 2025,
    "division_id": 5,
    "division": "Group C",
    "round": "Round 1 Quiz 1",
    "team_ids": [0, 12],
    "teams": ["Fin for Porpoise?", "Damaged Livers"],
    "venue_id": 0,
    "venue": "Elvis's Legs",
    "date": "2024-10-11",
    "time": "14:00",
    "scores": {
      "reader_id": 0,
      "reader": "Kayleigh Doyle",
      "scorer_id": 1,
      "scorer": "Grayson Monk",
      "player_ids": [[0, 4, 8, 1], [9, 2, 5, 6]],
      "players": [
        [
          "Grayson Monk",
          "Bill Thoms",
          "Allie Gardener",
          "Felipinho"
        ],
        [
          "John Yorkes",
          "Grant Marx",
          "Lacey Eastsome",
          "John Balliol"
        ]
      ],
      "captain_seats": [0, 3],
      "start_scores": [0, 8],
      "team_going_first": 1,
      "2s": [[6, 5, 4, 8], [5, 4, 6, 6]],
      "Xs": [[1, 2, 0, 0], [0, 0, 1, 2]],
      "1s": [[2, 3, 1, 4], [0, 3, 1, 1]],
      "scores": [56, 55],
      "round_houses": [1, 0],
      "close_loss": true,
      "finished": true,
    }
  },
  {
    "competition_id": 4,
    "competition": "Elected Official's Cup",
    "season_end_year": 2025,
    "division_id": 0,
    "division": "Division 0",
    "round": "Week 3",
    "team_ids": [2, 0],
    "teams": ["Piccalilli", "Cabbage"],
    "venue_id": 1,
    "venue": "The Hart and Courses",
    "date": "2024-10-13",
    "time": "14:00",
  },
  {
    "competition_id": 1,
    "competition": "Michaelmas League",
    "season_end_year": 2025,
    "division_id": 0,
    "division": "Division 0",
    "round": "Week 4",
    "team_ids": [2, 0],
    "teams": ["FEB", "Fin for Porpoise?"],
    "venue_id": 1,
    "venue": "The Cornish Centre",
    "date": "2024-10-15",
    "time": "20:00",
  },
]
